name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jason:v2

    - name: Checking version
      run: |
        uname -a
        
    - name: Checking docker processes
      run: |
        docker ps -a
        
     - name: Checking docker images
      run: |
        docker images
